version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ppob
    ports:
      - "1323:1323"
    env_file:
      - .env
    volumes:
      - /credentials:/mirror